name: fmt

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: check-formatting 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        #with:
        #  submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - run: zig fmt --check src/